require:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Enabled: true
  Max: 150

Naming/MethodParameterName:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Minitest/AssertInDelta:
  Enabled: false
